server:
  port: 8080
spring:
  application:
    name: hls-api
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/ngroute
    #username: root
    #password: root
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://200.200.1.3;DatabaseName=pubdata
    username: DXMMJ
    password: dxmmj
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.hls.api.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
# 日志配置
logging:
  level:
    com.hls: debug
    org.springframework: warn
